### ISSUE TITLE
blank index.xml renders

### ISSUE THREAD

**Issue by scivision** [de-souza/hugo-flex#11]
Ever since I started using hugo-flex several months ago, I noticed that any */index.xml yield a blank page or bare HTML code unprocessed.
It looks like maybe the code generating index.xml is not working as intended.
This becomes a real issue because search engines index and return high ranking results for these index.xml pages, which to users are blank or garbled.
My solution was to overload [rss.xml](https://github.com/scivision/hugo-flex-example/blob/master/layouts/_default/rss.xml) that gave only the plain xml for machine use, which search engines recognize not to put into human search results.

**Comment by de-souza** [comment]
Thank you for pointing this out. This fixes the issue with Google Chrome but not Internet Explorer…

**Comment by de-souza** [comment]
It should now work across all modern browsers.
