### ISSUE TITLE
showing page categories as well as tags

### ISSUE THREAD

**Issue by scivision** [de-souza/hugo-flex#12]
I like to list category as well as tag for each page. Does this seem like a reasonable options? Here's how I've been overloading this functionality:

I insert into my layouts/_default/single.html and layouts/index.html the line

```hugo
{{ partial "categories.html" . }}
```

referring to layouts/partials/categories.html containing

```hugo
{{ with .Params.categories }}
<footer>
  <ul class="Tags">
    {{ range . }}
    {{ $name := . }}
    {{ with $name | urlize | printf "/categories/%s" | site.GetPage }}
    <li class="Tags-item u-background">
      <a class="Tags-link u-clickable" href="{{ .Permalink }}" rel="category">{{ $name }}</a>
    </li>
    {{ end }}
    {{ end }}
  </ul>
</footer>
{{ end }}
```

**Comment by de-souza** [comment]
Thanks for pointing this out! From now on all taxonomy terms should be displayed under posts.

**Comment by scivision** [comment]
Thanks!
