### ISSUE TITLE
utterances not working

### ISSUE THREAD

**Issue by puhoy** [de-souza/hugo-flex#13]
for some reason, the $.Type variable is empty in comments.html. 
if i move the whole condition ( `{{ if in site.Params.mainSections $.Type | and site.Params.utterances.enable }}` ) from comments.html to single.html, it works.

also, "enable" should be "enabled" to match with the readme.

**Comment by de-souza** [comment]
Thank you very much for signaling this issue and providing debugging information. Utterances comments should be fixed now.
