### ISSUE TITLE
hugo-flex with dark mode

### ISSUE THREAD

**Issue by frenchvandal** [de-souza/hugo-flex#18]
Would you be interested in adding a dark mode version of your theme?

There are some tips [here](https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6) for example. To keep hugo-flex simple, I would not apply tip 7 (I guess a toggle or a let the system decide would require some `js`?) and just set the theme -light or dark- with a dedicated entry in the Hugo config file.

**Comment by scivision** [comment]
I would like to have dark mode, also.

**Comment by de-souza** [comment]
Fast forward 2023, now all major browsers support an automatic dark theme through the [color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) feature. This took literally two lines of code to implement.
