### ISSUE TITLE
Soundcloud Playback

### ISSUE THREAD

**Issue by 33nano** [de-souza/hugo-flex#20]
How exactly do i embed a soundcloud track to my hugo site?

I tried using the shortcode as suggested `{{< soundcloud 123456789 >}}` into the content of the markdown, but nothing shows up.

Do i have to modify the soundcloud.html file at all or leave it as is?

I have seen a number of hugo shortcodes for soundcloud, but nobody has given an actual practical example. Its all theoretical.

**Comment by de-souza** [comment]
Hello, there are different possible causes to your issue.

If you are trying to embed the shortcode in another site
The soundcloud.html file is using a mechanism from my blog to load its assets which are the soundcloud.css and soundcloud.js files.

If you'd like to use this file with another theme, the easiest would be to copy the three files in the same locations and add these lines in the beginning of the file _baseof.html of your theme:

<link rel="stylesheet" href="{{ .RelPermalink }}" integrity="{{ .Data.Integrity }}" crossorigin="anonymous">

**Comment by de-souza** [comment]
Hello, there are different possible causes to your issue.

### Embedding the soundcloud shortcode in a hugo site with another theme
 
The soundcloud shortcode is using a file from my theme called `assets.html` to load its assets on relevant pages. These assets are the `soundcloud.css` and `soundcloud.js` files. If you'd like to use this shortcode with another theme, the easiest way would be to copy the following files to your site:

- `hugo-flex/layouts/partials/assets.html` -> `your-hugo-site-root/layouts/partials/assets.html`
- `hugo-flex/layouts/shortcodes/soundcloud.html` -> `your-hugo-site-root/layouts/shortcodes/soundcloud.html`
- `hugo-flex/assets/css/soundcloud.css` -> `your-hugo-site-root/assets/css/soundcloud.css`
- `hugo-flex/assets/js/soundcloud.js` -> `your-hugo-site-root/assets/js/soundcloud.js`

Finally, find a way to load the file `assets.html` in your theme, insinde the `<header>` section of the html page. The `assets.html` file is called a "partial", and there might be a section in the documentation of your theme explaining you how to add your own partials to the theme. If not, copy this file from your theme to your website:

- `your-theme/layouts/_default/baseof.html` -> `your-hugo-site-root/layouts/_default/baseof.html`

Then, edit it and add the following line at the end of the `<header>` section:

```html
<header>
...
...
{{ partial "assets.html" . }}
</header>
```

(you can see an example of this in the file `hugo-flex/layouts/_default/baseof.html` from my theme)

### If Soundcloud is blocked by the browser

If the console of your web browser is showing you errors when you load the page with the soundcloud player, it might be that your website is asking your browser to block all connections to external websites.

If that's the case, you must find a way to change this setting in your website. In my case, I used the following file to tell my host netlify to send the message "block every website except soundcloud". The file is located at `my-hugo-site-root/static/_headers`:

```
/*
  Content-Security-Policy: default-src 'self'; script-src https://identity.netlify.com https://unpkg.com 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src data: 'self'; frame-src https://w.soundcloud.com;
  X-Content-Type-Options: nosniff
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
```

Hope this helps, feel free to answer if you have questions.

**Comment by 33nano** [comment]
Thank you very much. That honestly covers a lot. I'm glad I asked. I thought it was only 1 file, but turns outs the CSS and JavaScript files are needed as well. I did run into that issue regarding the Content Security Policy, now I know how to fix it. I'll close this issue once, I get on over to my PC, currently writing this from the Fasthub Android app.
