### ISSUE TITLE
Custom css not working as expected

### ISSUE THREAD

**Issue by karpfen** [de-souza/hugo-flex#21]
Hi, first of all, thanks for providing this theme!
I tried customizing my page a bit with an external css file like shown in the `README`, but I can't get it to load.

I created a style file `static/css/foo.css`, containing some syle instructions.
In `config.yaml`, I added

```
css:
  - css/foo.css
```

When building the page, the `foo.css` file shows up in the correct place in the `public` folder. But there is no reference to it anywhere. Am I doing something wrong in my config file or is this a bug in the theme?

**Comment by de-souza** [comment]
Hi, thanks for your support. Could you please try to place the files in the `assets` folder rather than the `static` folder? In any case I should improve the explanation on how to do this, thanks for pointing it out.

**Comment by karpfen** [comment]
This solved it for me. Thank you!
