### ISSUE TITLE
provide css through script instead of inline

### ISSUE THREAD

**Issue by samueletonon** [de-souza/hugo-flex#3]
Hello!

thanks for providing this nice template I am relly liking it!
Unfortunately this template has CSS inline in the HTML, which conflicts with usual CSP configuration .

A temporary workaround is to put the CSP header with  

style-src 'self' 'unsafe-inline'

however, as the name suggest this is unsafe as it might open the website to attacks if later someone has a sub directory where users can write something. To avoid this it would be awesome if you could provide the css through a file instead of loading it inline; do you think this is possible ?

**Comment by de-souza** [comment]
Thank you very much for your suggestion. Content security policy should function from now on.
