### ISSUE TITLE
Do you have an Example Site?

### ISSUE THREAD

**Issue by MatthewMcD** [de-souza/hugo-flex#4]
I am interested in creating a site, but there is no "Example Site" in your theme. Do you have a sample? I can build one up but thought I'd ask first.

**Comment by de-souza** [comment]
Hello, the official hugoBasicExample may be used as an example site, I've added a link in the README. Thank you for your suggestion.

**Comment by MatthewMcD** [comment]
OK, thanks. I'll give it a shot. I had to guess at a few of the configuration items.
